version: '3.5'
services: 
  admin:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    depends_on: 
      - admin_db

  admin_db:
    image: mysql:5.7.22
    tty: true
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - /dbdata:/var/lib/mysql
    ports: 
      - 33060:3306

      

